id: A61F7F2DD
title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru from
  Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.614050
  last_modified_at: 2022-03-01 03:37:28.614052
