id: A61F7F2DD
title: A Prayer to Shower Down the Rain of Wisdom
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.603450
  last_modified_at: 2022-03-01 03:37:28.603453
