id: A61F7F2DD
title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin Nyima
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.615459
  last_modified_at: 2022-03-01 03:37:28.615462
