id: A61F7F2DD
title: Prayer to the Gurus of the Dzogchen Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.606744
  last_modified_at: 2022-03-01 03:37:28.606747
