id: A61F7F2DD
title: Dzogchen Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.605372
  last_modified_at: 2022-03-01 03:37:28.605376
