id: A61F7F2DD
title: A Dzogchen Tögal Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:37:28.601582
  last_modified_at: 2022-03-01 03:37:28.601590
